### ISSUE TITLE
Suggestion: React Stateless Functional Components:

### ISSUE THREAD

**Issue by jck-d-rpr** [gdad-s-river/gdad-s-river-blog-github#1]
here take a look at [this](https://medium.com/@joshblack/stateless-components-in-react-0-14-f9798f8b992d#.v6kikbmmm)

**Comment by gdad-s-river** [comment]
Thanks @jck-d-rpr , I know about them :) I took this course which explained them in detail : courses.reactjsprogram.com/courses/reactjsfundamentals . I just copy pasted someone's implementation of gatsby static site generator, will keep refactoring and adding stuff slowly and steadily :) What up with you these days ? Let's connect over reactjs IRC (gdad-s-river)

**Comment by jck-d-rpr** [comment]
ok
